version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /mobile_app
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /realtime_agent
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /infrastructure
    schedule:
      interval: weekly

