include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    directives_ordering: true
    prefer_single_quotes: true
    use_super_parameters: true
